name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérification des fichiers requis
        run: |
          test -f frontend/index.html
          test -f frontend/app.js

      - name: Affichage du contenu du dossier frontend
        run: |
          echo "Contenu du dossier frontend :"
          ls -l frontend
      - name: Check secrets presence
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "USERNAME MISSING"; fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "PASSWORD MISSING"; fi
      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construction et push de l'image Docker frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/databird-api:frontend-latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/databird-api:frontend-latest
